# Generated by Django 6.0.6 on 2026-06-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-creado'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pago',
            name='plan',
            field=models.CharField(default='Mensual', max_length=30),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(default='Aprobado', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(default='Tarjeta', max_length=30),
        ),
    ]
