# Generated by Django 6.0.6 on 2026-06-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_options_pago_numero_factura_pago_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='iva',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
