# Generated by Django 6.0.6 on 2026-09-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_pasarela_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosuscripcion',
            name='tipo',
            field=models.CharField(choices=[('Activacion', 'Activacion'), ('Renovacion', 'Renovacion'), ('Cancelacion', 'Cancelacion'), ('Vencimiento', 'Vencimiento'), ('AjusteAdmin', 'AjusteAdmin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Anulado', 'Anulado'), ('Error', 'Error')], default='Pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Reembolso',
        ),
    ]
