# Generated by Django 6.0.6 on 2026-10-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_quitar_reembolsos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosuscripcion',
            name='tipo',
            field=models.CharField(choices=[('Activacion', 'Activación'), ('Renovacion', 'Renovación'), ('Cancelacion', 'Cancelación'), ('Vencimiento', 'Vencimiento'), ('AjusteAdmin', 'Ajuste del administrador')], max_length=20),
        ),
    ]
