# Generated by Django 6.0.6 on 2026-07-11 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroApuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=30)),
                ('fecha', models.CharField(blank=True, max_length=12)),
                ('equipo_local', models.CharField(max_length=80)),
                ('equipo_visitante', models.CharField(max_length=80)),
                ('liga', models.CharField(blank=True, max_length=80)),
                ('mercado', models.CharField(max_length=30)),
                ('icono', models.CharField(blank=True, max_length=8)),
                ('etiqueta', models.CharField(max_length=120)),
                ('probabilidad', models.FloatField(default=0)),
                ('acierto', models.BooleanField(default=False)),
                ('propia', models.BooleanField(default=False)),
                ('cuota', models.FloatField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'apuesta registrada',
                'verbose_name_plural': 'apuestas registradas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='BibliotecaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('partidos', models.JSONField(default=list)),
                ('guardado', models.CharField(blank=True, max_length=40)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_biblioteca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'equipo de biblioteca',
                'verbose_name_plural': 'biblioteca de equipos',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='PartidoRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=30)),
                ('fecha', models.CharField(blank=True, max_length=12)),
                ('equipo_local', models.CharField(max_length=80)),
                ('equipo_visitante', models.CharField(max_length=80)),
                ('liga', models.CharField(blank=True, max_length=80)),
                ('datos', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'partido registrado',
                'verbose_name_plural': 'partidos registrados',
                'unique_together': {('usuario', 'referencia')},
            },
        ),
    ]
