# Generated by Django 6.0.6 on 2026-09-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0004_temperatura_sin_mercado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BibliotecaEquipo',
        ),
    ]
