# Generated by Django 6.0.6 on 2026-09-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analizador', '0005_quitar_biblioteca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesosmotor',
            name='tramos',
        ),
    ]
