# Generated by Django 6.0.6 on 2026-09-23 03:49

from django.db import migrations, models


def pasar_fotos_a_la_base(apps, schema_editor):
    #Las fotos que ya estan en disco se copian a la base. Si el archivo ya no
    #existe (en Railway se borra en cada despliegue) se deja el perfil sin
    #foto: mostrar una imagen rota es peor que mostrar la inicial.
    from usuarios.validaciones import foto_a_data_uri
    Perfil = apps.get_model("usuarios", "Perfil")
    for perfil in Perfil.objects.exclude(avatar="").exclude(avatar__isnull=True):
        try:
            with perfil.avatar.open("rb") as archivo:
                perfil.foto = foto_a_data_uri(archivo)
        except Exception:
            pass
        perfil.avatar = None
        perfil.save(update_fields=["foto", "avatar"])


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_documento_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(pasar_fotos_a_la_base, migrations.RunPython.noop),
    ]
