# Generated by Django 6.0.6 on 2026-09-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_foto_en_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='avatar',
        ),
    ]
