# Generated by Django 6.0.6 on 2026-10-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_quitar_avatar_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='idioma',
            field=models.CharField(default='es', max_length=8),
        ),
    ]
