"""
Django settings for xgol project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#Cargar las variables de entorno desde el archivo .env
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'inicio',
    'usuarios',
    'analizador',
    'suscripciones',
    'pagos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]
ROOT_URLCONF = 'xgol.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.rol_actual',
            ],
        },
    },
]

WSGI_APPLICATION = 'xgol.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# la carpeta static de la raiz para albergar el diseño y la logica del proyecto

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#albergar las imagenes del proyecto
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#Ejecutar las configuraciones de smtp de gmail para la recuperacion de contraseña
EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST="smtp.gmail.com"
EMAIL_USE_TLS=True
EMAIL_PORT=587
EMAIL_HOST_USER=os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD=os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL=os.getenv('EMAIL_HOST_USER')

#Token de football-data.org para los partidos del inicio
FOOTBALL_DATA_TOKEN = os.getenv('FOOTBALL_DATA_TOKEN')

#Configurar allauth para el inicio de sesion con Google
SITE_ID=1
ACCOUNT_ADAPTER='usuarios.adapters.AdaptadorCuenta'

AUTHENTICATION_BACKENDS=[
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


LOGIN_REDIRECT_URL='/'
ACCOUNT_LOGOUT_REDIRECT_URL='/'

#Conectar automaticamente la cuenta de Google si el correo ya existe
SOCIALACCOUNT_EMAIL_AUTHENTICATION=True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT=True

#Entrar directo con Google sin pantallas intermedias
SOCIALACCOUNT_LOGIN_ON_GET=True

#Configurar el proveedor de Google
SOCIALACCOUNT_PROVIDERS={
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

# ============================================================
#  PASARELA DE PAGOS — Wompi
#  Las llaves viven en .env, nunca aqui.
# ============================================================
WOMPI_AMBIENTE=os.getenv('WOMPI_AMBIENTE','test')
WOMPI_LLAVE_PUBLICA=os.getenv('WOMPI_LLAVE_PUBLICA','')
WOMPI_LLAVE_PRIVADA=os.getenv('WOMPI_LLAVE_PRIVADA','')
WOMPI_SECRETO_INTEGRIDAD=os.getenv('WOMPI_SECRETO_INTEGRIDAD','')
WOMPI_SECRETO_EVENTOS=os.getenv('WOMPI_SECRETO_EVENTOS','')

#URL publica del sitio, con https y sin barra final. En local va vacia.
PAGOS_URL_BASE=os.getenv('PAGOS_URL_BASE','')

#Tarifas para ESTIMAR la comision y proyectar el neto en los reportes.
#La cifra real es la que liquida Wompi en su extracto.
TARIFAS_PASARELA={
    'CARD':                 {'porcentaje':2.99,'fijo':600, 'iva':0.19},
    'PSE':                  {'porcentaje':1.49,'fijo':1200,'iva':0.19},
    'NEQUI':                {'porcentaje':1.79,'fijo':0,   'iva':0.19},
    'BANCOLOMBIA_TRANSFER': {'porcentaje':1.50,'fijo':0,   'iva':0.19},
    'BANCOLOMBIA_COLLECT':  {'porcentaje':0.00,'fijo':2500,'iva':0.19},
    'MANUAL':               {'porcentaje':0.00,'fijo':0,   'iva':0.00},
    'DEFECTO':              {'porcentaje':2.99,'fijo':600, 'iva':0.19},
}


# ============================================================
#  ZONA HORARIA
#  Los datos siguen guardandose en UTC (USE_TZ=True). Esto solo cambia como
#  se agrupan y se muestran, para que "ingresos de hoy" no quede corrido.
# ============================================================
TIME_ZONE='America/Bogota'


# ============================================================
#  CACHE COMPARTIDA
#  LocMemCache es por proceso: con varios workers cada uno tiene la suya.
#  DatabaseCache no agrega dependencias. Crear la tabla una sola vez con:
#     python manage.py createcachetable
# ============================================================
CACHES={
    'default':{
        'BACKEND':'django.core.cache.backends.db.DatabaseCache',
        'LOCATION':'cache_xgol',
        'TIMEOUT':300,
        'OPTIONS':{'MAX_ENTRIES':5000},
    }
}


# ============================================================
#  ORIGENES DE CONFIANZA
#  Django compara el header Origin en toda peticion HTTPS, tambien con
#  DEBUG=True. Detras de un tunel o un proxy el navegador manda https:// y el
#  servidor local corre en http://: sin esta lista, cada POST devuelve 403.
# ============================================================
CSRF_TRUSTED_ORIGINS=[o for o in os.getenv('CSRF_TRUSTED_ORIGINS','').split(',') if o]


# ============================================================
#  SEGURIDAD EN PRODUCCION
#  Solo se activa con DEBUG=False. En local no cambia nada.
# ============================================================
if not DEBUG:
    SECURE_PROXY_SSL_HEADER=('HTTP_X_FORWARDED_PROTO','https')
    SECURE_SSL_REDIRECT=True
    SESSION_COOKIE_SECURE=True
    CSRF_COOKIE_SECURE=True
    SECURE_HSTS_SECONDS=31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS=True
    SECURE_HSTS_PRELOAD=True
    SECURE_CONTENT_TYPE_NOSNIFF=True
    SESSION_COOKIE_HTTPONLY=True
    X_FRAME_OPTIONS='DENY'
    