# Generated by Django 6.0.6 on 2026-06-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_solicitud',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='solicitada',
            field=models.BooleanField(default=False),
        ),
    ]
