# Generated by Django 6.0.6 on 2026-06-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_suscripcion_fecha_solicitud_suscripcion_solicitada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='fecha_solicitud',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='solicitada',
        ),
    ]
